### ISSUE TITLE
Switch add card button to search component map

### ISSUE THREAD

**Issue by grassfinn** [grassfinn/MtgCollection#3]
The button is a part of the card component, so when you hover over it, it doesn't look like the card is hovering due to the button being transformed.  The card should be the only piece that transforms not the button as well.

**Comment by Nababratadeb-NITA** [comment]
hey @grassfinn i want to work on this issue 
I can fix this for you.

**Comment by grassfinn** [comment]
Sounds good @Nababratadeb-NITA. Thank you!

**Comment by Nababratadeb-NITA** [comment]
Hey @grassfinn you want the card only to transform right not the button

**Comment by grassfinn** [comment]
> Hey @grassfinn you want the card only to transform right not the button

Yes, but the functionality of the button should still work.

**Comment by grassfinn** [comment]
@Nababratadeb-NITA It looks great! the only thing I change is I commented out the price part.

**Comment by Nababratadeb-NITA** [comment]
Great 
Can you please star my repo if possible
